ignoredBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - extract-file-icon
  - lzma-native

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - extract-file-icon
  - lzma-native
